# Generated by Django 2.1.5 on 2019-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Book')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('link', models.CharField(max_length=256, verbose_name='Link')),
            ],
        ),
    ]
